config/routes.rb
# coding: UTF-8

Notearkiv::Application.routes.draw do

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'login_once/:code' => 'user_sessions#new_once', :as => :onelogin

  match 'forgotten_password' => 'user_sessions#forgotten', :as => :forgot
  match 'reset_password' => 'user_sessions#reset', :as => :reset

  match 'download/:prefix/:type/:file.:format' => 'archive#download', :as => :download

  match 'search' => 'search#search', :as => :search
  match 'results' => 'search#results', :as => :results
  match 'search/advanced/note' => 'search#adv_search_notes', :as => :notesearch
  match 'search/advanced/evensong' => 'search#adv_search_evensongs', :as => :evensongsearch
  match 'results/advanced/note' => 'search#adv_results_notes', :as => :noteresults
  match 'results/advanced/evensong' => 'search#adv_results_evensongs', :as => :evensongresults


  resources :user_sessions
  resources :users
  resources :stats
  resources :periods
  resources :genres
  resources :composers
  resources :languages
  resources :notes
  resources :evensongs
  resources :account
  resources :links

  match "/menu" => "menu#index", :as => :menu

  match 'db_auth' => 'session_caches#authorize', :as => :authorize

  match 'upload/notes' => 'notes_upload#upload', :as => :notesupload
  match 'upload/notes/import' => 'notes_upload#import', :as => :notesimport

  match 'upload/evensongs' => 'evensongs_upload#upload', :as => :evensongsupload
  match 'upload/evensongs/import' => 'evensongs_upload#import', :as => :evensongsimport


  root :to => "notes#index"
end

app/models/note.rb
# coding: UTF-8

class Note < ActiveRecord::Base
  include Attachable
  include Importable

  attr_accessor :doc_file, :music_file

  before_destroy :remove_files
  before_destroy :remove_links

  belongs_to :composer
  belongs_to :genre
  belongs_to :period

  has_many :note_language_assignments
  has_many :languages, :through => :note_language_assignments

  has_many :links

  delegate :name, :to => :genre, :prefix => true, :allow_nil => true
  delegate :name, :to => :composer, :prefix => true, :allow_nil => true
  delegate :name, :to => :period, :prefix => true, :allow_nil => true

  before_validation(:on => :create){ set_next_item }

  validates_presence_of :item, :title, :count_originals

  after_save :upload

  scope :ordered, :order => 'title ASC'
  scope :preloaded, :include => [:composer, :genre, :period, :languages, :links]

  EXCEL_HEADERS = [HeaderColumn.new("SysID", 8),
                   HeaderColumn.new("ID", 8),
                   HeaderColumn.new("Tittel", 50),
                   HeaderColumn.new("Komponist", 35),
                   HeaderColumn.new("Genre", 35),
                   HeaderColumn.new("Epoke", 35),
                   HeaderColumn.new("Språk", 35),
                   HeaderColumn.new("Akkomp.", 35),
                   HeaderColumn.new("Original", 8),
                   HeaderColumn.new("Kopi", 8),
                   HeaderColumn.new("Instr.", 8),
                   HeaderColumn.new("Besetning", 15),
                   HeaderColumn.new("Solister", 35),
                   HeaderColumn.new("Kommentar", 50)].freeze

  DOCUMENT_TITLE = 'Notearkiv'.freeze

  def self.suggest_voice(search)
    Note.select('distinct voice').where(:voice.matches => search + '%').order('voice').map(&:voice)
  end

  def self.simple_search(search)
    notes = Note.where(:title.matches => '%' + search + '%')
    notes << Composer.where(:name.matches => '%' + search + '%').map(&:notes)
    notes.flatten.uniq.sort{|a,b| a.title <=> b.title}
  end

  def self.excel
    NoteSheet.new(EXCEL_HEADERS,
                  Note.ordered.preloaded,
                  DOCUMENT_TITLE,
                  lambda { |row, item|
                    langs = item.languages.map { |lang| lang.name }

                    row.push item.id
                    row.push item.item
                    row.push item.title
                    row.push item.composer ? item.composer.name : ""
                    row.push item.genre ? item.genre.name : ""
                    row.push item.period ? item.period.name : ""
                    row.push langs.join(", ")
                    row.push item.instrument
                    row.push item.count_originals
                    row.push item.count_copies
                    row.push item.count_instrumental
                    row.push item.voice
                    row.push item.soloists
                    row.push item.comment
                  })
  end

  def self.import(file)
    ImportLog.delete_all

    importer = Importer.new(file,
                            EXCEL_HEADERS.map { |header| header.title })

    importer.rows.each_with_index do |row, i|
      item = {:sysid => row[0],
              :id => row[1],
              :title => row[2],
              :composer => row[3],
              :genre => row[4],
              :epoch => row[5],
              :languages => import_language_list(row[6]),
              :instrument => row[7],
              :original => row[8],
              :copy => row[9],
              :instrumental => row[10],
              :voice => row[11],
              :solo => row[12],
              :comment => row[13]}

      note = find_existing_if_present(item[:sysid])

      note.import_item(item, i + 2)
    end
  end


  def populate_from_import(item)
    # Mandatory fields
    self.title = item[:title]
    self.count_originals = item[:original]

    # Optional fields - allows overwriting with blank
    self.soloists = item[:solo]
    self.count_copies = item[:copy]
    self.count_instrumental = item[:instrumental]
    self.comment = item[:comment]
    self.voice = item[:voice]
    self.instrument = item[:instrument]

    self.period = item[:epoch].blank? ? nil : Period.find_or_create_by_name(item[:epoch])
    self.composer = item[:composer].blank? ? nil : Composer.find_or_create_by_name(item[:composer])
    self.genre = item[:genre].blank? ? nil : Genre.find_or_create_by_name(item[:genre])

    langs = Array.new
    if (!item[:languages].blank?)
      item[:languages].each do |lang|
        langs << Language.find_or_create_by_name(lang)
      end
    end
    self.languages = langs
  end

  private

  def set_next_item
    self.item = Note.maximum(:item) + 1
  end

  def upload
    self.doc_url = upload_file get_doc_uploader(:note), @doc_file
    self.music_url = upload_file get_music_uploader(:note), @music_file

    # Can't call save - that would recurse. Send a message to the update_without_callbacks method
    self.send(:update_without_callbacks)
  end

  def self.import_language_list(languages)
    languages.blank? ? nil : languages.split(", ")
  end

  def self.find_existing_if_present(id)
    return Note.new if id.blank?

    if (Note.exists? id)
      Note.find(id)
    else
      Note.new
    end
  end

  def remove_links
    self.links.each do |link|
      link.destroy
    end
  end
end

app/controllers/notes_controller.rb
# coding: UTF-8

class NotesController < ApplicationController
  filter_access_to :all

  before_filter :get_note, :only => [:show, :edit, :update, :destroy]

  def index
    set_accept_header
    @notes = Note.ordered.preloaded

    prawnto :prawn => {:page_layout=>:landscape, :top_margin => 10, :bottom_margin => 10}, :inline => false,
            :filename => "Notearkiv_#{Date.today().strftime("%Y-%m-%d")}.pdf"

    respond_to do |format|
      format.html # index.html.erb
      format.txt { index_suggest_voices }
      format.pdf
      format.xls { index_excel }
    end
  end

  def import
  end

  def show
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(params[:note])

    if @note.save
      flash[:notice] = 'Note opprettet.'
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    if @note.update_attributes(params[:note])
      flash[:notice] = 'Note oppdatert.'
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end

  def destroy
    flash[:notice] = "Note #{@note.title} slettet."

    @note.destroy

    redirect_to(notes_url)
  end

  private

  def index_excel
    excel = Note.excel

    send_file(excel.get_spreadsheet,
              :type => 'application/vnd.ms-excel',
              :disposition => 'attachment',
              :filename => excel.get_filename)
  end

  def index_suggest_voices
    send_data Note.suggest_voice(params[:q].downcase).join("\n"),
              :type => 'text/plain',
              :disposition => 'inline'
  end

  def get_note
    @note = Note.find(params[:id])
  end
end

app/views/notes/_note.erb
<% content_for :head do %>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#note_voice").autocomplete('<%= notes_path(:format => :txt) %>');
        });
    </script>
<% end %>


<%= semantic_form_for @note, :html => {:enctype => "multipart/form-data"} do |form| %>
    <%= form.inputs do %>
        <%= form.input :title, :label => "Tittel" %>
        <%= form.input :composer, :label => "Komponist", :required => false, :collection => Composer.ordered %>
        <%= form.input :period, :label => "Epoke", :required => false, :collection => Period.ordered %>
        <%= form.input :genre, :label => "Genre", :required => false, :collection => Genre.ordered %>
        <%= form.input :languages, :label => "Språk", :required => false, :collection => Language.ordered %>
        <%= form.input :instrument, :label => "Akkomp.", :required => false %>
        <%= form.input :voice, :label => "Besetning", :required => false %>
        <%= form.input :soloists, :label => "Solister", :required => false %>
        <%= form.input :count_originals, :label => "Antall original" %>
        <%= form.input :count_copies, :label => "Antall kopi", :required => false %>
        <%= form.input :count_instrumental, :label => "Antall instrumental", :required => false %>
        <%= form.input :comment, :label => "Kommentar", :required => false, :input_html => {:rows => 5} %>
        <%= form.input :doc_file, :label => "PDF/ZIP", :as => :file, :required => false %>
        <%= form.input :music_file, :label => "MP3/M4A/ZIP", :as => :file, :required => false %>
    <% end %>
    <%= form.buttons do %>
        <%= form.commit_button :label => "Lagre" %>
    <% end %>
<% end %>

app/views/notes/_notes.html.erb
<table id="noteTable">
  <thead>
  <tr>
    <th>ID</th>
    <th>Tittel</th>
    <th>Komponist</th>
    <th>Genre</th>
    <th>Epoke</th>
    <th>Språk</th>
    <th>Akkomp.</th>
    <th>Lenker</th>
  </tr>
  </thead>
  <tbody>
  <%= render :partial => '/notes/notes_row', :collection => @notes, :as => :note %>
  </tbody>
</table>

app/views/notes/_notes_links.html.erb
<% content_for :links do %>
    <div class="box">
      <h2>Noter</h2>
      <ul>
        <% if permitted_to? :new, :notes %>
            <li><%= link_to 'Ny note', new_note_path %></li>
        <% end %>
        <% if permitted_to? :upload, :notes_upload %>
            <li><%= link_to 'Last opp', notesupload_path %></li>
        <% end %>
        <li><%= link_to 'Last ned (xls)', notes_path(:format => :xls) %></li>
        <li><%= link_to 'Last ned (pdf)', notes_path(:format => :pdf) %></li>
      </ul>
    </div>
<% end %>

app/views/notes/_notes_row.html.erb
<tr>
  <td>
    <%= link_to(note) do %>
        <%= note.item %>
    <% end %>
  </td>
  <td>
    <%= link_to(note) do %>
        <%= note.title %>
    <% end %>
  </td>
  <td><%= note.composer.name if note.composer %></td>
  <td><%= note.genre.name if note.genre %></td>
  <td><%= note.period.name if note.period %></td>
  <td>
    <% if note.languages.size() > 0 %>
        <ul>
          <% note.languages.each do |lang| %>
              <li><%= lang.name %></li>
          <% end %>
        </ul>
    <% end %>
  </td>
  <td><%= note.instrument %></td>
  <td>
    <% if (!note.has_attachment?) && permitted_to?(:edit, note) %>
        <%= link_to 'Last&nbsp;opp'.html_safe, edit_note_path(note) %>
    <% else %>
        <%= list_link_dropbox_files(note) %>
    <% end %>
    <ul class="external">
      <% if permitted_to?(:show, :links) %>
          <% if note.links %>
              <% note.links.each do |link| %>
                  <li><%= link_to link.title, link.url, :class => 'link_out' %></li>
              <% end %>
          <% end %>
      <% end %>
      <% if permitted_to?(:new, :links) %>
          <li><%= link_to 'Ny lenke', new_link_path(:note => note.id) %></li>
      <% end %>
    </ul>
  </td>
</tr>

app/views/notes/edit.html.erb
<h1>Endre <%= @note.title %></h1>

<%= render :partial => "note", :locals => { :note => @note } %>


<% content_for :links do %>
    <div class="box">
      <h2>Note</h2>
      <ul>
        <li><%= link_to 'Tilbake til noter', notes_path %></li>
      </ul>
    </div>
<% end %>

app/views/notes/index.html.erb
<h2>Noter</h2>

<%= render :partial => 'notes_links' %>

<%= render :partial => 'notes' %>

app/views/notes/new.html.erb
<h1>Ny note</h1>

<%= render :partial => "note", :locals => { :note => @note } %>

<% content_for :links do %>
    <div class="box">
      <h2>Note</h2>
      <ul>
        <li><%= link_to 'Tilbake til noter', notes_path %></li>
      </ul>
    </div>
<% end %>

app/views/notes/show.html.erb
<h2>Note: <%= @note.title %></h2>

<br/>

<table>

  <tr>
    <td>ID</td>
    <td><%= @note.item %></td>
  </tr>

  <tr>
    <td>Tittel</td>
    <td><%= @note.title %></td>
  </tr>

  <tr>
    <td>Komponist</td>
    <td>
      <%= @note.composer_name %>
    </td>
  </tr>

  <tr>
    <td>Genre</td>
    <td>
      <%= @note.genre_name %>
    </td>
  </tr>

  <tr>
    <td>Epoke</td>
    <td>
      <%= @note.period_name %>
    </td>
  </tr>

  <tr>
    <td>Språk</td>
    <td>
      <% if @note.languages.size() > 0 %>
          <ul>
            <% @note.languages.each do |lang| %>
                <li><%= lang.name %></li>
            <% end %>
          </ul>
      <% end %>
    </td>
  </tr>

  <tr>
    <td>Akkomp.</td>
    <td>
      <%= @note.instrument %>
    </td>
  </tr>

  <tr>
    <td>Besetning</td>
    <td><%= @note.voice %></td>
  </tr>

  <tr>
    <td>Solister</td>
    <td><%= @note.soloists %></td>
  </tr>

  <tr>
    <td>Antall original</td>
    <td><%= @note.count_originals %></td>
  </tr>

  <tr>
    <td>Antall kopi</td>
    <td><%= @note.count_copies %></td>
  </tr>

  <tr>
    <td>Antall instrumental</td>
    <td><%= @note.count_instrumental %></td>
  </tr>

  <tr>
    <td>Kommentar</td>
    <td>
      <%= @note.comment %>
    </td>
  </tr>

  <tr>
    <td>Fil</td>
    <td><%= list_link_dropbox_files(@note) %></td>
  </tr>

  <% if permitted_to?(:show, :links) %>
      <tr>
        <td>Lenker</td>
        <td>
          <ul>
            <% @note.links.each do |link| %>
                <li>
                  <% if permitted_to?(:edit, :links) %>
                      <%= link_to '[R] ', edit_link_path(link), :title => "Rediger" %>
                  <% end %>
                  <% if permitted_to?(:destroy, :links) %>
                      <%= link_to '[S] ', link, :title => "Slett", :confirm => 'Sikker?', :method => :delete %>
                  <% end %>
                  <%= link_to link.title, link.url, :class => 'link_out' %>
                </li>
            <% end %>
            <% if permitted_to?(:new, :links) %>
                <li>
                  <%= link_to 'Ny lenke', new_link_path(:note => @note.id) %>
                </li>
            <% end %>
          </ul>
        </td>
      </tr>
  <% end %>
</table>

<% content_for :links do %>
    <div class="box">
      <h2>Note</h2>
      <ul>
        <% if permitted_to? :edit, @note %>
            <li><%= link_to 'Endre', edit_note_path %></li>
        <% end %>
        <% if permitted_to? :destroy, @note %>
            <li><%= link_to 'Slett', @note, :confirm => 'Sikker?', :method => :delete %></li>
        <% end %>
        <li><%= link_to 'Tilbake til noter', notes_path %></li>
      </ul>
    </div>
<% end %>