config/routes.rb
# coding: UTF-8

Notearkiv::Application.routes.draw do

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'login_once/:code' => 'user_sessions#new_once', :as => :onelogin

  match 'forgotten_password' => 'user_sessions#forgotten', :as => :forgot
  match 'reset_password' => 'user_sessions#reset', :as => :reset

  match 'download/:prefix/:type/:file.:format' => 'archive#download', :as => :download

  match 'search' => 'search#search', :as => :search
  match 'results' => 'search#results', :as => :results
  match 'search/advanced/note' => 'search#adv_search_notes', :as => :notesearch
  match 'search/advanced/evensong' => 'search#adv_search_evensongs', :as => :evensongsearch
  match 'results/advanced/note' => 'search#adv_results_notes', :as => :noteresults
  match 'results/advanced/evensong' => 'search#adv_results_evensongs', :as => :evensongresults


  resources :user_sessions
  resources :users
  resources :stats
  resources :periods
  resources :genres
  resources :composers
  resources :languages
  resources :notes
  resources :evensongs
  resources :account
  resources :links

  match "/menu" => "menu#index", :as => :menu

  match 'db_auth' => 'session_caches#authorize', :as => :authorize

  match 'upload/notes' => 'notes_upload#upload', :as => :notesupload
  match 'upload/notes/import' => 'notes_upload#import', :as => :notesimport

  match 'upload/evensongs' => 'evensongs_upload#upload', :as => :evensongsupload
  match 'upload/evensongs/import' => 'evensongs_upload#import', :as => :evensongsimport


  root :to => "notes#index"
end

app/models/period.rb
# coding: UTF-8

class Period < ActiveRecord::Base
  has_many :notes

  validates_presence_of :name

  scope :ordered, :order => 'name ASC'
  scope :preloaded, :include => [:notes]
end

app/controllers/periods_controller.rb
# coding: UTF-8

class PeriodsController < ApplicationController
  filter_access_to :all

  before_filter :get_period, :only => [:edit, :update, :destroy]

  def index
    @periods = Period.ordered.preloaded
  end

  def new
    @period = Period.new
  end

  def create
    @period = Period.new(params[:period])

    if @period.save
      flash[:notice] = 'Epoke opprettet.'
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    @period.name = params["period"]["name"]

    if @period.save
      flash[:notice] = 'Epoke oppdatert.'
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end

  def destroy
    flash[:notice] = "Epoke #{@period.name} slettet."

    @period.destroy

    redirect_to(periods_url)
  end

  private

  def get_period
    @period = Period.find(params[:id])
  end

end

app/views/periods/_back_links.html.erb
<% content_for :links do %>
    <div class="box">
      <h2>Epoke</h2>
      <ul>
        <li><%= link_to 'Tilbake til epoker', periods_path %></li>
      </ul>
    </div>
<% end %>

app/views/periods/_period.erb
<%= semantic_form_for period do |form| %>
    <%= form.inputs do %>
       <%= form.input :name, :label => "Epoke" %>
    <% end %>
    <%= form.buttons do %>
        <%= form.commit_button :label => "Lagre" %>
    <% end %>
<% end %>

app/views/periods/edit.html.erb
<h1>Endre <%= @period.name %></h1>

<%= render :partial => "period", :locals => { :period => @period } %>

<%= render :partial => 'back_links' %>

app/views/periods/index.html.erb
<h2>Epoker</h2>

<br/>

<table>

  <% for period in @periods %>
      <tr>
        <td><%= h period.name %></td>
        <% if permitted_to? :edit, period %>
            <td><%= link_to 'endre', edit_period_path(period) %></td>
        <% end %>
        <% if permitted_to? :destroy, period %>
            <td>
              <% if period.notes.size() == 0 %>
                  <%= link_to 'slett', period, :confirm => 'Er du sikker?',
                              :method => :delete %>
              <% else %>
                  <ul>
                    <% if period.notes.size() > 0 %>
                        <li>
                          <%= period.notes.size() %>
                          <% if period.notes.size() == 1 %>
                              note
                          <% else %>
                              noter
                          <% end %>
                        </li>
                    <% end %>
                  </ul>
              <% end %>
            </td>
        <% end %>
      </tr>
  <% end %>
</table>

<% if permitted_to? :new, :periods %>
    <% content_for :links do %>
        <div class="box">
          <h2>Epoker</h2>
          <ul>
            <li><%= link_to 'Ny epoke', new_period_path %></li>
          </ul>
        </div>
    <% end %>
<% end %>

app/views/periods/new.html.erb
<h1>Ny epoke</h1>

<%= render :partial => "period", :locals => { :period => @period } %>

<%= render :partial => 'back_links' %>