config/routes.rb
# coding: UTF-8

Notearkiv::Application.routes.draw do

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'login_once/:code' => 'user_sessions#new_once', :as => :onelogin

  match 'forgotten_password' => 'user_sessions#forgotten', :as => :forgot
  match 'reset_password' => 'user_sessions#reset', :as => :reset

  match 'download/:prefix/:type/:file.:format' => 'archive#download', :as => :download

  match 'search' => 'search#search', :as => :search
  match 'results' => 'search#results', :as => :results
  match 'search/advanced/note' => 'search#adv_search_notes', :as => :notesearch
  match 'search/advanced/evensong' => 'search#adv_search_evensongs', :as => :evensongsearch
  match 'results/advanced/note' => 'search#adv_results_notes', :as => :noteresults
  match 'results/advanced/evensong' => 'search#adv_results_evensongs', :as => :evensongresults


  resources :user_sessions
  resources :users
  resources :stats
  resources :periods
  resources :genres
  resources :composers
  resources :languages
  resources :notes
  resources :evensongs
  resources :account
  resources :links

  match "/menu" => "menu#index", :as => :menu

  match 'db_auth' => 'session_caches#authorize', :as => :authorize

  match 'upload/notes' => 'notes_upload#upload', :as => :notesupload
  match 'upload/notes/import' => 'notes_upload#import', :as => :notesimport

  match 'upload/evensongs' => 'evensongs_upload#upload', :as => :evensongsupload
  match 'upload/evensongs/import' => 'evensongs_upload#import', :as => :evensongsimport


  root :to => "notes#index"
end

app/models/language.rb
# coding: UTF-8

class Language < ActiveRecord::Base
  has_many :note_language_assignments
  has_many :notes, :through => :note_language_assignments

 validates_presence_of :name

  scope :ordered, :order => 'name ASC'
  scope :preloaded, :include => [:notes]
end

app/controllers/languages_controller.rb
# coding: UTF-8

class LanguagesController < ApplicationController
  filter_access_to :all

  before_filter :get_language, :only => [:edit, :update, :destroy]


  def index
    @languages = Language.ordered.preloaded
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(params[:language])

    if @language.save
      flash[:notice] = 'Språk opprettet.'
      redirect_to :action => "index"
    else
      render :action => "new"
    end
  end

  def edit
  end

  def update
    @language.name = params["language"]["name"]

    if @language.save
      flash[:notice] = 'Språk oppdatert.'
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end

  def destroy
    @language = Language.find(params[:id])

    flash[:notice] = "Språk #{@language.name} slettet."

    @language.destroy

    redirect_to(languages_url)
  end

  private

  def get_language
    @language = Language.find(params[:id])
  end

end

app/views/languages/_back_links.html.erb
<% content_for :links do %>
    <div class="box">
      <h2>Språk</h2>
      <ul>
        <li><%= link_to 'Tilbake til språk', languages_path %></li>
      </ul>
    </div>
<% end %>

app/views/languages/_language.erb
<%= semantic_form_for language do |form| %>
    <%= form.inputs do %>
       <%= form.input :name, :label => "Språk" %>
    <% end %>
    <%= form.buttons do %>
        <%= form.commit_button :label => "Lagre" %>
    <% end %>
<% end %>

app/views/languages/edit.html.erb
<h1>Endre <%= @language.name %></h1>

<%= render :partial => "language", :locals => { :language => @language } %>

<%= render :partial => 'back_links' %>

app/views/languages/index.html.erb
<h2>Språk</h2>

<br/>

<table>

  <% for language in @languages %>
      <tr>
        <td><%= h language.name %></td>
        <% if permitted_to? :edit, language %>
            <td><%= link_to 'endre', edit_language_path(language) %></td>
        <% end %>
        <% if permitted_to? :destroy, language %>
            <td>
              <% if language.notes.size() == 0 %>
                   <%= link_to 'slett', language, :confirm => 'Er du sikker?',
                               :method => :delete %>
               <% else %>
                   <ul>
                     <% if language.notes.size() > 0 %>
                         <li>
                           <%= language.notes.size() %>
                           <% if language.notes.size() == 1 %>
                               note
                           <% else %>
                               noter
                           <% end %>
                         </li>
                     <% end %>
                   </ul>
               <% end %>
            </td>
        <% end %>
      </tr>
  <% end %>
</table>

<% if permitted_to? :new, :languages %>
    <% content_for :links do %>
        <div class="box">
          <h2>Epoker</h2>
          <ul>
            <li><%= link_to 'Ny språk', new_language_path %></li>
          </ul>
        </div>
    <% end %>
<% end %>

app/views/languages/new.html.erb
<h1>Ny språk</h1>

<%= render :partial => "language", :locals => { :language => @language }  %>

<%= render :partial => 'back_links' %>