config/routes.rb
# coding: UTF-8

Notearkiv::Application.routes.draw do

  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  match 'login_once/:code' => 'user_sessions#new_once', :as => :onelogin

  match 'forgotten_password' => 'user_sessions#forgotten', :as => :forgot
  match 'reset_password' => 'user_sessions#reset', :as => :reset

  match 'download/:prefix/:type/:file.:format' => 'archive#download', :as => :download

  match 'search' => 'search#search', :as => :search
  match 'results' => 'search#results', :as => :results
  match 'search/advanced/note' => 'search#adv_search_notes', :as => :notesearch
  match 'search/advanced/evensong' => 'search#adv_search_evensongs', :as => :evensongsearch
  match 'results/advanced/note' => 'search#adv_results_notes', :as => :noteresults
  match 'results/advanced/evensong' => 'search#adv_results_evensongs', :as => :evensongresults


  resources :user_sessions
  resources :users
  resources :stats
  resources :periods
  resources :genres
  resources :composers
  resources :languages
  resources :notes
  resources :evensongs
  resources :account
  resources :links

  match "/menu" => "menu#index", :as => :menu

  match 'db_auth' => 'session_caches#authorize', :as => :authorize

  match 'upload/notes' => 'notes_upload#upload', :as => :notesupload
  match 'upload/notes/import' => 'notes_upload#import', :as => :notesimport

  match 'upload/evensongs' => 'evensongs_upload#upload', :as => :evensongsupload
  match 'upload/evensongs/import' => 'evensongs_upload#import', :as => :evensongsimport


  root :to => "notes#index"
end

app/models/user.rb
# coding: UTF-8

require 'digest/sha1'

class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.logged_in_timeout(30.minutes)
  end

  has_many :user_role_assignments
  has_many :roles, :through => :user_role_assignments

  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end

  def one_time_code
    self.onetime = Digest::SHA1.hexdigest("onetime #{Time.now} #{current_login_ip}")

    self.save

    self.onetime
  end

  def send_reset_password
    code = one_time_code

    Arkiv.reset_password(self, code).deliver
  end

  def clear_one_time_code
    self.onetime = nil

    self.save
  end

  def display_name
    name.blank? ? username : name
  end

  def update_from_user_params(user)
    self.email = user["email"]
    self.password = user["password"]
    self.password_confirmation = user["password_confirmation"]
  end
end

app/controllers/users_controller.rb
# coding: UTF-8

class UsersController < ApplicationController
  filter_access_to :all

  before_filter :get_user, :only => [:edit, :show, :update]

  def index
    @users = User.all
  end

  def edit
  end

  def show
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = 'Bruker oppdatert.'
      redirect_to :action => "index"
    else
      render :action => "edit"
    end
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

end

app/views/users/edit.html.erb
<%= semantic_form_for @user do |form| %>
    <%= form.inputs do %>
        <%= form.input :name, :label => "Navn" %>
        <%= form.input :email, :label => "E-post" %>
        <%= form.input :roles, :label => "Roles", :as => :check_boxes %>
    <% end %>
    <%= form.buttons do %>
        <%= form.commit_button :label => "Lagre" %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<h2>Brukere</h2>

<table id="userTable">
  <thead>
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th>E-mail</th>
    <th>Updated</th>
    <th>Login Count</th>
    <th>Failed Login Count</th>
    <th>Last Request</th>
    <th>Current Login</th>
    <th>Current Login IP</th>
    <th>Roles</th>
  </tr>
  </thead>
  <tbody>
  <% for user in @users %>
      <tr>
        <td>
          <%= link_to user.username, user_path(user) %>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td>
          <%= user.email %>
        </td>
        <td>
          <%= user.updated_at %>
        </td>
        <td>
          <%= user.login_count %>
        </td>
        <td>
          <%= user.failed_login_count %>
        </td>
        <td>
          <%= user.last_request_at %>
        </td>
        <td>
          <%= user.current_login_at %>
        </td>
        <td>
          <%= user.current_login_ip %>
        </td>
        <td>
          <ul>
            <% user.roles.each do |role| %>
                <li><%= role.name %></li>
            <% end %>
          </ul>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h2>User: <%= @user.username %></h2>

<br/>

<table>

  <tr>
    <td>Email</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>Name</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td>Created</td>
    <td>
      <%= @user.created_at %>
    </td>
  </tr>
  <tr>
    <td>Updated</td>
    <td>
      <%= @user.updated_at %>
    </td>
  </tr>
  <tr>
    <td>Login Count</td>
    <td>
      <%= @user.login_count %>
    </td>
  </tr>
  <tr>
    <td>Failed Login Count</td>
    <td>
      <%= @user.failed_login_count %>
    </td>
  </tr>
  <tr>
    <td>Last Request</td>
    <td>
      <%= @user.last_request_at %>
    </td>
  </tr>
  <tr>
    <td>Current Login</td>
    <td>
      <%= @user.current_login_at %>
    </td>
  </tr>
  <tr>
    <td>Last Login</td>
    <td>
      <%= @user.last_login_at %>
    </td>
  </tr>
  <tr>
    <td>Current Login IP</td>
    <td>
      <%= @user.current_login_ip %>
    </td>
  </tr>
  <tr>
    <td>Last Login IP</td>
    <td>
      <%= @user.last_login_ip %>
    </td>
  </tr>
  <tr>
    <td>Roles</td>
    <td>
      <ul>
        <% @user.roles.each do |role| %>
            <li><%= role.name %></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

<br/>

<% if permitted_to? :edit, @user %>
    <%= link_to 'Endre', edit_user_path(@user) %>
    |
<% end %>

<% if permitted_to? :index, :users %>
    <%= link_to 'Back to users', users_path %>
<% end %>